project:
  type: website

website:
  title: "quiz02"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Life Exp vs GDP"
        href: life-gdp.qmd
      - text: "Life Exp vs Population"
        href: life-population.qmd
      - text: "Country Over Time"
        href: country.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

output-dir: docs


